[package]
name = "simple_sysctl"
version = "0.1.0"
authors = ["djnn <email@djnn.sh>"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
linux-kernel-module = { path = ".." }

[profile.release]
panic = "abort"
lto = true

[profile.dev]
panic = "abort"
